### ISSUE TITLE
CI/CT/CD

### ISSUE THREAD

**Issue by Rjvs** [StirlingLabs/flatcc#1]
## Integration & Testing

- We need library, CLI & Runtime (`flatcc`, `flatcc-cli` & `flatccrt`) built for Win64, MacOS, Linux with the flag `-DFLATCC_OFFSET_SIZE=8` (store them as artefacts if they pass the tests).
- PRs created to bring updates from upstream, same as XKCP & meshoptimizer
- Coverage as per the others too

## Deployment

Store binaries as part of the tagged Release artefacts.

**Comment by TYoungSL** [comment]
For building on Windows,

Additional Prerequisites:
* MSys2 (MinGW64)

Build Steps (from MinGW64 bash shell):
```sh
mkdir -p build/mingw64
cd build/mingw64
cmake -G "MinGW Makefiles" ../.. -DBUILD_SHARED_LIBS=ON -DFLATCC_OFFSET_SIZE=8 -DCMAKE_BUILD_TYPE=Release
cmake --build . --target flatcc_cli --config Release
cmake --build . --target flatccrt --config Release
```

**Comment by TYoungSL** [comment]
[StirlingLabs.flatcc-win64.zip](https://github.com/StirlingLabs/flatcc/files/6901401/StirlingLabs.flatcc-win64.zip)

**Comment by TYoungSL** [comment]
For building on other platforms,
```sh
mkdir -p build/mingw64
cd build/mingw64
cmake ../.. -DBUILD_SHARED_LIBS=ON -DFLATCC_OFFSET_SIZE=8 -DCMAKE_BUILD_TYPE=Release
cmake --build . --target flatcc_cli --config Release
cmake --build . --target flatccrt --config Release
```

**Comment by TYoungSL** [comment]
Expect (most) tests to fail as they are still expecting 32-bit offsets.
